modLoader="javafml"
loaderVersion="[43,)"
license="GNU Lesser General Public License version 3 (LGPLv3)"

[[mods]]
modId="the_eom_mod"
version="1.1.0"
displayName="Elemental on Minecraft"
credits="Textures and Recipes done by CreateSource and TheWeirdNerdyGamer"
displayURL="https://abnormalhare.github.io"
authors="CreateSource"
description='''
Elemental on Discord copied to Minecraft
'''

[[dependencies.the_eom_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




