modLoader="javafml"
loaderVersion="[47,)"
license="GNU Lesser General Public License version 3 (LGPLv3)"

[[mods]]
modId="eommod"
version="1.1.0"
displayName="Elemental on Minecraft"
displayURL="https://abnormalhare.github.io"
credits="Textures and Recipes done by CreateSource and TheWeirdNerdyGamer"
authors="CreateSource"
description="Elemental on Discord copied to Minecraft"

[[dependencies.eommod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




